
import sqlite3
import random

class WikiGetSentence(object):
    def __init__(self,f_data ="/home/mukhlis/machine_learning_nlp"):
        self.filepath = f_data
        try:
            self._db_connection = sqlite3.connect(self.filepath)
            self._db_cur = self._db_connection.cursor()
        except Error as e:
            print(e)

    def query(self, query, params=""):
        return self._db_cur.execute(query, params)

    def generate_list(self, tabel, ukuran, max_count):
        ukur = 0
        daftar_id = []
        toks=[]
        l = list(range(max_count))
        random.shuffle(l)
        print("randomize...")
        a = ""
        indeks = 0
        while ((indeks < max_count) and (ukur <= ukuran)):
            self._db_cur.execute("select id,dokumen, ukuran from {df_tabel} where id = {df_acak}+1".format(df_tabel=tabel,df_acak=l[indeks]))
            (id_nya, dokumen, ukuran_data) = self._db_cur.fetchone()
            # select limit 1 offset acak
            # ambil id dan ukuran_data
            daftar_id.append(id_nya)
            toks.append(dokumen.replace('\n',' '))
            ukur = ukur + ukuran_data
            indeks = indeks+1
            if indeks%2000==0:
                print("Suffeling {0:.2f}%".format((ukur/ukuran)*100))
        return toks, daftar_id

    def generate_sentence(self, lang, max_len, size, outputfile=''):
        if lang=='id':
            generate_id(max_len,size)

        if outputfile=='':
            savedb(lang, sentences)
        else:
            savefile(lang,sentences, outputfile)

    def generate_id(self,max_len,size):
        # generate indonesia sentences with max lengh of sentences max_len and count of sentences size
        pass

    def savedb(self,lang,sentences):
        # saving sentences list generated by generate sentences to database
        pass

    def savefile(self,lang,sentences,outputfile):
        # saving sentences generated by generate sentences function to text file
        pass



if __name__ == '__main__':
    count_id = 408734
    sumber = 'wiki_id'
    ukuran = 10000
    wikiget = WikiGetSentence()
    b, daftarnya = wikiget.generate_list(sumber, ukuran, count_id)
    print(b[0])
    print(b[1])
    print(b[2])
